apiVersion: v1
kind: Secret
metadata:
  name: aiops-secrets
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GITLAB_URL: {{ .Values.secrets.gitlabUrl | quote }}
  GITLAB_TOKEN: {{ .Values.secrets.gitlabToken | quote }}
  GITLAB_WEBHOOK_SECRET: {{ .Values.secrets.gitlabWebhookSecret | quote }}
  SONARQUBE_TOKEN: {{ .Values.secrets.sonarqubeToken | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
